application: netprintbox-alpha
version: dev
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /task/.*
  script: bootstrap.app
  login: admin
- url: /static
  static_dir: static
- url: /.*
  script: bootstrap.app

builtins:
- admin_redirect: on
- datastore_admin: on
- deferred: on
- remote_api: on

skip_files: |
  ^(.*/)?(
  (.git/.*)|
  (app\.yaml)|
  (Rakefile)|
  (.*\.py[co])|
  (tests/.*)|
  (script/.*)|
  )$
