application: netprintbox
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /task/.*
  script: main.app
  login: admin
- url: /.*
  script: main.app

builtins:
- admin_redirect: on
- datastore_admin: on
- deferred: on
- remote_api: on
